name: diff

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  contents: write
  checks: read

jobs:
  ilock:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    steps:
      - name: ilock
        uses: github/lock@v2.1.1
        with:
          environment: global
          lock_trigger: /lock
          unlock_trigger: /unlock
          lock_info_alias: /wcid
  unlock:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
    steps:
      - name: unlock
        uses: github/lock@v2.1.1
        with:
          environment: global
          mode: unlock
  diff:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/diff') }}
    steps:
      - name: acknowledge
        uses: GrantBirki/comment@v2.0.7
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes

      - name: lock
        id: lock
        uses: github/lock@v2.1.1
        with:
          environment: servera
          mode: check

      - name: locked_comment
        uses: GrantBirki/comment@v2.0.7
        if: ${{ steps.lock.outputs.locked == 'true' && steps.lock.outputs.created_by != github.actor }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This repo is currently locked by ${{ steps.lock.outputs.created_by }}. Please wait for them to finish before trying again.

      - name: acquire_lock
        uses: github/lock@v2.1.1
        if: ${{ steps.lock.outputs.locked == 'false' }}
        with:
          environment: global
          mode: lock

      - name: install_tools
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: |
            argocd 2.8.4

      - name: diff
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hello, world!"
            });

      - name: success
        uses: GrantBirki/comment@v2.0.7
        if: ${{ success() }}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"

      - name: failure
        uses: GrantBirki/comment@v2.0.7
        if: ${{ failure() }}
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "-1"
