name: deploy

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: github/lock@v2.1.1
        id: lock
        with:
          mode: check
          environment: global

      - uses: github/lock@v2.1.1
        if: contains(github.event.comment.body, '.diff')
        with:
          mode: lock
          environment: global
          reason: diff

      - name: diff
        if: contains(github.event.comment.body, '.diff')
        run: |
          echo "Doing diff stuff on ${{ github.event.issue.pull_request.head.ref }}"

      # - name: branch-deploy
      #   id: branch-deploy
      #   uses: imranismail/branch-deploy@main
      #   with:
      #     allow_forks: false
      #     disable_naked_commands: true
      #     noop_trigger: .diff
      #     trigger_message_template: |
      #       {% set deploymentType = "diff" if noop else "deployment" %}
      #       ### {{ deploymentType | title }} Triggered 🚀

      #       {{ actor }} started a {{ deploymentType | lower }} to **{{ environment }}**

      #       You can watch the progress [here]({{ log_url }}) 🔗
      #     deploy_message_template: |
      #       {% set deploymentType = "diff" if noop else "deploy" %}
      #       {% set emoji = "⚠️" %}
      #       {% set message = ["**", actor, "**", " ", deploymentType, "ed",  "ref", " ", "`", ref, "`"] %}
      #       {% if status === "success" -%}
      #         {% set emoji = "✅" %}
      #         {% set message = ["**", actor, "**", " ", "successfully", " ", deploymentType, "ed" ," ", "ref", " ", "`", ref, "`", " ", "to", " ", "**", environment, "**"] %}
      #       {%- elif status === "failure" -%}
      #         {% set emoji = "❌" %}
      #         {% set message = ["**", actor, "**", " ", "had a failure when", " ", deploymentType, "ing", " ", "ref", " ", "`", ref, "`", "to", " ", "**", environment, "**"] %}
      #       {%- endif %}

      #       ### {{ "Deployment" if deploymentType == "deploy" else "Diff" }} Results {{ emoji }}

      #       {{ message | join }}

      # - name: diff
      #   if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
      #   shell: bash
      #   run: |
      #     echo "Doing diff stuff on ${{steps.branch-deploy.outputs.environment}}"

      # - name: deploy
      #   if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
      #   shell: bash
      #   run: |
      #     echo "Doing deploy stuff on ${{steps.branch-deploy.outputs.environment}}"
