name: diff

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    strategy:
      matrix:
        include:
          - env: server1
            server: https://server1.example.com
          - env: server2
            server: https://server2.example.com
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v8.1.0
        with:
          stable_branch: master
          allow_forks: false
          trigger: .diff
          environment: ${{ matrix.env }}
          environment_urls: "${{ matrix.env }}|${{ matrix.server }}"

      - name: checkout
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}

      - name: diff
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        shell: bash
        run: |
          echo "Doing diff stuff on ${{steps.branch-deploy.outputs.environment}}"
