name: diff

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    strategy:
      matrix:
        include:
          - env: server1
            server: https://server1.example.com
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: imranismail/branch-deploy@main
        with:
          allow_forks: false
          environment: ${{ matrix.env }}
          environment_urls: "${{ matrix.env }}|${{ matrix.server }}"
          trigger: .diff
          trigger_message_template: |
            ### Diff Triggered 🚀

            {{ actor }} started a {{ deployment_type | lower }} diff to **{{ environment_url }}**

            You can watch the progress [here]({{ log_url }}) 🔗

            > {{ deployment_type }}: `{{ ref }}`
          deploy_message_template: |
            {% set deploymentType = " **noop** " if noop else " " %}
            {% set emoji = "⚠️" %}
            {% set message = ["Warning:", deploymentType, "diffing status is unknown, please use caution"] %}
            {% if status === "success" -%}
              {% set emoji = "✅" %}
              {% set message = ["**", actor, "**", " successfully", deploymentType, "diffed branch `", ref, "` to **", environment, "**"] %}
            {%- elif status === "failure" -%}
              {% set emoji = "❌" %}
              {% set message = ["**", actor, "**", " had a failure when", deploymentType, "diffing branch `", ref, "` to **", environment, "**"] %}
            {%- endif %}

            ### Diff Results {{ emoji }}

            {{ message | join }}


      - name: diff
        if: ${{ steps.branch-deploy.outputs.continue == 'true' }}
        shell: bash
        run: |
          echo "Doing diff stuff on ${{steps.branch-deploy.outputs.environment}}"
